platform/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'images/random'

  resources :articles
  resources :images
  #resources :images do
  #  get 'random', on: :collection
  #en
  root 'images#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

platform/app/models/ann.rb
class Ann < ApplicationRecord
  belongs_to :image
  has_many :bboxes, dependent: :destroy
  enum flag: [:ground, :eval]
end

platform/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

platform/app/models/article.rb
class Article < ApplicationRecord
end

platform/app/models/bbox.rb
class Bbox < ApplicationRecord

  belongs_to :bbox
end

platform/app/models/image.rb
class Image < ApplicationRecord

  has_attached_file :text_image, :url  => "/image_trans/:id/:filename",
     :path => ":rails_root/public/image_trans/:id/:filename"
  validates :text_image, attachment_presence: true
  validates_attachment_content_type :text_image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  has_many :anns, dependent: :destroy
end

platform/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

platform/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def index
		respond_to do |format|
			format.html
			format.json
		end
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		uri = URI.parse("http://0.0.0.0:8000")
		http = Net::HTTP.new(uri.host, uri.port)
		request = Net::HTTP::Post.new("/predict")
		response = http.request(request)

		@aux = Article.new
		@aux.title = response.body	
		@aux.text = response.body

 		respond_to do |format|
 			if @article.save
 				format.js {render 'show'}	
 			end
 		end
  		
	end

	def show
	end

	private
		def article_params
    		params.require(:article).permit(:title, :text)
  		end
end

platform/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  BOUNDARY = "AaB03x"
  def index
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.create(image_params)

    respond_to do |format|
      if @image.save
        path = "#{Rails.root}/public/image_trans/" + @image.id.to_s + "/" + @image.text_image_file_name 
        #response = RestClient.post 'http://0.0.0.0:9000/get_sentence', :imgProcessing => File.new(path, 'rb')

        @aux = Ann.new


        format.js {render 'show'} 
      end
    end
  end

  def random
    @image = Image.order("RANDOM()").first
    if @image
      redirect_to edit_image_path(@image.id)
    else
      redirect_to new_image_path
    end
  end

  def edit
    @image = Image.find(params[:id])
    @path = "/image_trans/" + @image.id.to_s + "/" + @image.text_image_file_name
  end

  def update
  end

  private
    def image_params
      params.require(:image).permit(:text_image)
    end

end

platform/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

platform/app/helpers/application_helper.rb
module ApplicationHelper
end

platform/app/helpers/articles_helper.rb
module ArticlesHelper
end

platform/app/helpers/images_helper.rb
module ImagesHelper
end

platform/app/helpers/welcome_helper.rb
module WelcomeHelper
end

platform/app/views/articles/_form.html.erb
<%= form_with scope: @article, remote: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

platform/app/views/articles/create.js.erb
$('#tasks').html("<%= j (render @tasks) %>");
$('#task-form').slideUp(350);

platform/app/views/articles/index.html.erb
<%= link_to 'create', new_article_path%>

platform/app/views/articles/new.html.erb
<%= form_for @article, :html=>{:id=>"lalala", :multipart => true, remote: true} do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>
<div id="divNuevo">
  
</div>

platform/app/views/articles/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

platform/app/views/articles/show.html.erb
<p>lalsdalsdjsa</p>

platform/app/views/articles/show.js.erb
$("#divNuevo").html("<div><p><%=@aux.title%></p></div>")

platform/app/views/images/edit.html.erb
<section>
  <div id='transcription_view'>
    <canvas id='canvas_edit' width="0" height="0"></canvas>
    <%= image_tag(@path, :alt => "image_trans") %>
  </div>
  <div>
    <%= link_to 'Next', images_random_path %>
  </div>
</section>

platform/app/views/images/new.html.erb
<div id="divNuevo">
  
</div>

<section>
  <div>
    <%= form_for @image, html: {multipart: true, remote: true} do |form| %>
      <%= form.file_field :text_image , id: "upload_image",  required: true%>
      <%= submit_tag "Transcript", id: "btn_submit_image" %>
    <% end %>
  </div>
  <div id='transcription_view'>
    <canvas id='myCanvas' width="0" height="0"></canvas>
    <div id='upload_image_view'>  </div>
  </div>
  <div id='transcription_text'>
    <textarea id=transcription placeholder="Upload an image to see a transcription" cols="150", rows="10"></textarea>
  </div>
  <div>
    <%= link_to 'Collaborate', images_random_path %>
  </div>
</section>

platform/app/views/images/show.js.erb
$(document).ready(function() {
  $("#transcription").text("<%=%>")

  console.log("lalala");
  var img = $("#img_preview");
  console.log(img);
  var cnvs = $("#myCanvas")[0];
  console.log("lalalalalal");
  console.log(cnvs);

  cnvs.width = 400;
  cnvs.height = 500;
  cnvs.style.left = img.offsetLeft + "px";
  cnvs.style.top = img.offsetTop + "px";
        
  var aux = "<%= @aux %>"
  var ctx = cnvs.getContext('2d');
  ctx.beginPath();
  ctx.rect(aux.x0, aux.y0, aux.x1, aux.y1);
  ctx.rect(90, 40, 150, 100);
  ctx.lineWidth = 3;
  ctx.strokeStyle = '#00ff00';
  ctx.stroke();
});

platform/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platform</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

platform/app/views/welcome/index.html.erb
<%= link_to 'Back', new_transcription_path %>